### ISSUE TITLE
ActiveRecord Database adapter

### ISSUE THREAD

**Issue by numbata** [numbata/reindexer-ruby#50]
In the world full of 🦄 and 🦋 it would be nice to easily do something like this:
```yaml
# database.yml

reindexer_production:
  adapter: reindexer_grps
  host: reindexer
  database: animals_app_production
  port: 16536
  migrations_paths: db/reindexer_migrations
```

```ruby
# Migration
class CreateDogsIndex < ActiveRecord::Migration[7.0]
  def change
    create_table :dogs_index do |t|
      t.string :name
      t.integer :age
  
      t.timestamps
    end
  end
end

# Models
class ReindexerRecord < ActiveRecord::Base
  self.abstract_class = true

  establish_connection :reindexer_production 
end

class DogsIndex < ReindexerRecord
  self.table_name = :dogs_index # namespace in terms of Reindexer
end

DogsIndex.create!(name: "Laika", age: 2)
DogsIndex.first_by(name: "Laika")
```
